name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: install.packages(c("xml2", "rvest"))
      - run: Rscript -e 'source("ci/Build.R")'
